done

diff --git a/run b/run
--- a/run
+++ b/run
@@ -45,23 +45,27 @@ if [[ $file != *.agl ]]; then
     exit 1
 fi
 
+if [ ! -f $file ]; then
+    echo "File not found!"
+    usage
+    exit 1
+fi
+
 file="../$file" # Prepend the path to the file
 cd src
 # Processing logic based on the presence of -s flag
 if [ $semCheck = "false" ]; then
-    cat $file | antlr4-run > ../__agl__run.py
+    java AGLMain $file > ../__agl__run.py
     cd ..
     python3 __agl__run.py
-    rm __agl__run.py
     exit 0
 fi    
 
 if cat $file | java RunSemTests 2>&1 | grep -q "Semantic check passed."; then
     echo -e "\e[32m $(basename "$file"): Semantic Test OK\e[0m"
-    cat $file | antlr4-run > ../__agl__run.py
+    java AGLMain $file > ../__agl__run.py
     cd ..
     python3 __agl__run.py
-    rm __agl__run.py
 else
     echo -e "\e[31m $(basename "$file"): Semantic Test FAIL\e[0m" 
     cat $file | java RunSemTests
